### PR TITLE
feat: create Action type and send_with_callback

### PR DESCRIPTION
**Pull request by willemneal**
This adds a new function `send_with_callback`, which takes a contract with a function `link_callback(account_id)`, and the gas required for the call.

To handle this change I added an Action enum to replace the Balance value type in the map:
```rust
pub enum Action {
  Deposit(Balance),
  DepositCallBack(Balance, AccountId, Gas, Balance),
}
```

Then when responding to claims the it checks the action to determine if a call back is added to the promise chain.

- [ ] Add final attached deposit required by callback

### CODE REVIEW

**Comment by mattlockyer** [comment]
I see where you're going with it. Could be really useful to kick off a cross contract call after linkdrop is claimed.

e.g. I deploy this linkdrop proxy, call send_with_callback (restricted to only_owner) then a callback NFT contract and method could mint a free NFT, only for calls with predecessor of the linkdrop proxy contract.

**Comment by willemneal** [comment]
Bingo!  That is exactly my plan.

**Comment by mattlockyer** [comment]
Yea cause then we don't have to redeploy our linkdrop proxy contracts to do "new things" with linkdrops. We can just keep creating them and changing the send_with_callback args. Great idea! Love the composability!

**Comment by willemneal** [comment]
@mattlockyer Just realized that we need to add a way to specify how much attached deposit is required for the final callback.

But in other news, I've tested it with my newest project and realized I forgot about the attached deposit when the callback returns.

**Pull request closed without merging**
